window.buildLivingDemoData = function buildLivingDemoData() {
  const areaSeeds = [
    {
      id: "terrace",
      name: "Terraza",
      icon: "Terrace",
      capacity: 40,
      reservationFee: 120,
      deposit: 300,
      requiresApproval: true,
      requiresGuestList: false,
      requiresCleaning: true,
      requiresInspection: true,
      rules: ["Máximo 6 horas", "Termina antes de las 11:00 PM", "Garantía obligatoria", "Cargo de limpieza obligatorio"],
      location: "Torre A · Piso 22",
      status: "active",
    },
    {
      id: "bbq",
      name: "Zona BBQ",
      icon: "BBQ",
      capacity: 20,
      reservationFee: 60,
      deposit: 150,
      requiresApproval: false,
      requiresGuestList: false,
      requiresCleaning: true,
      requiresInspection: false,
      rules: ["Máximo 4 horas", "Sin música amplificada"],
      location: "Torre B · Piso 22",
      status: "active",
    },
    {
      id: "event-room",
      name: "Salón de eventos",
      icon: "Events",
      capacity: 60,
      reservationFee: 200,
      deposit: 500,
      requiresApproval: true,
      requiresGuestList: true,
      requiresCleaning: true,
      requiresInspection: true,
      rules: ["Aprobación previa", "Lista de invitados obligatoria"],
      location: "Torre A · Piso 1",
      status: "active",
    },
    {
      id: "coworking",
      name: "Coworking",
      icon: "Coworking",
      capacity: 12,
      reservationFee: 0,
      deposit: 0,
      requiresApproval: false,
      requiresGuestList: false,
      requiresCleaning: false,
      requiresInspection: false,
      rules: ["Solo residentes", "Sin garantía"],
      location: "Torre A · Piso 2",
      status: "active",
    },
    {
      id: "gym",
      name: "Gimnasio",
      icon: "Gym",
      capacity: 30,
      reservationFee: 0,
      deposit: 0,
      requiresApproval: false,
      requiresGuestList: false,
      requiresCleaning: false,
      requiresInspection: false,
      rules: ["No requiere reserva"],
      location: "Torre B · Piso 3",
      status: "active",
    },
  ];

  const areas = areaSeeds.map((area) => {
    const reservable = area.id !== "gym";
    const policy = {
      id: `${area.id}-policy-v1`,
      version: 1,
      effectiveFrom: "2026-01-01",
      name: area.name,
      location: area.location,
      capacity: area.capacity,
      rules: [...area.rules],
      reservable,
      status: area.status,
      closureReason: null,
      payment: { enabled: area.reservationFee > 0, amount: area.reservationFee, methods: ["Yape", "Plin", "Transferencia"] },
      guarantee: { enabled: area.deposit > 0, amount: area.deposit, methods: ["Yape", "Plin", "Transferencia"] },
      availability: { months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], weekdays: [1, 2, 3, 4, 5, 6, 0], start: area.id === "terrace" ? "09:00" : "08:00", end: area.id === "terrace" ? "23:00" : "22:00", blockMinutes: area.id === "coworking" ? 60 : 120, maxDurationMinutes: area.id === "terrace" ? 360 : area.id === "bbq" ? 240 : 480 },
      requirements: { guestList: area.requiresGuestList, approval: area.requiresApproval },
      createdAt: "2026-01-01T09:00:00-05:00",
      createdBy: "María Fernanda Rojas",
    };
    return { ...area, policyVersions: [policy] };
  });

  const coreResidents = [
    { apartment: "402", tower: "A", name: "Ana García", phone: "+51 987 654 321", email: "ana.garcia@example.com", status: "active", debt: 0, relationship: "Propietaria" },
    { apartment: "605", tower: "A", name: "José Torres", phone: "+51 934 111 222", email: "jose.torres@example.com", status: "active", debt: 0, relationship: "Propietario" },
    { apartment: "808", tower: "A", name: "Valeria Mendoza", phone: "+51 955 444 777", email: "valeria.mendoza@example.com", status: "active", debt: 0, relationship: "Propietaria" },
    { apartment: "1203", tower: "B", name: "Miguel Castro", phone: "+51 922 888 333", email: "miguel.castro@example.com", status: "active", debt: 0, relationship: "Propietario" },
    { apartment: "1507", tower: "B", name: "Lucía Fernández", phone: "+51 977 123 987", email: "lucia.fernandez@example.com", status: "active", debt: 0, relationship: "Propietaria" },
  ];

  const firstNames = ["Mariana", "Sebastián", "Camila", "Ignacio", "Daniela", "Fernando", "Gabriela", "Andrés", "Carolina", "Renato", "Paola", "Alonso", "Claudia", "Mateo", "Jimena", "Diego", "Sandra", "Rodrigo", "Elena", "Piero"];
  const lastNames = ["Paredes", "Salas", "Muñoz", "Torres", "Flores", "Ruiz", "León", "Díaz", "Gómez", "Sánchez", "Rivas", "Quispe", "Navarro", "Lozano", "Ramírez", "Luna", "Morales", "Acuña", "Vargas", "Delgado"];
  const fillerResidents = [];
  const occupied = new Set(coreResidents.map((resident) => resident.apartment));

  let floor = 2;
  let unit = 1;
  let residentIndex = 0;
  while (fillerResidents.length < 47) {
    const apartment = `${floor}${String(unit).padStart(2, "0")}`;
    unit += 1;
    if (unit > 8) {
      unit = 1;
      floor += 1;
    }
    if (occupied.has(apartment)) continue;
    const firstName = firstNames[residentIndex % firstNames.length];
    const lastName = lastNames[(residentIndex * 3) % lastNames.length];
    fillerResidents.push({
      apartment,
      tower: floor > 11 ? "B" : "A",
      name: `${firstName} ${lastName}`,
      phone: `+51 9${String(10000000 + residentIndex * 731).slice(0, 8)}`,
      email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`,
      status: residentIndex % 13 === 0 ? "blocked" : "active",
      debt: residentIndex % 9 === 0 ? 180 : 0,
      relationship: residentIndex % 5 === 0 ? "Inquilino" : "Propietario",
    });
    residentIndex += 1;
  }

  const residents = [...coreResidents, ...fillerResidents].map((resident) => ({
    id: window.livingUid("resident", resident.apartment),
    ...resident,
  }));

  const apartments = Array.from({ length: 168 }, (_, index) => {
    const floorNumber = Math.floor(index / 8) + 1;
    const unitNumber = (index % 8) + 1;
    const apartment = `${floorNumber}${String(unitNumber).padStart(2, "0")}`;
    const resident = residents.find((item) => item.apartment === apartment);
    return {
      id: window.livingUid("apartment", apartment),
      tower: floorNumber > 11 ? "B" : "A",
      apartment,
      residentName: resident ? resident.name : "Sin asignar",
      whatsapp: resident ? resident.phone : "Sin registro",
      residentStatus: resident ? resident.status : "pending",
      debtStatus: resident && resident.debt > 0 ? "Deuda" : "Al día",
    };
  });

  const guestListAna = [
    "Andrea Paredes", "Luis Salas", "Diego Muñoz", "Carmen Torres", "Patricia Flores",
    "Jorge Ruiz", "Sofía León", "Ricardo Díaz", "Elena Gómez", "Pedro Sánchez",
    "Luciana Rivas", "Álvaro Navarro", "María Quispe", "Ricardo Lozano", "Nadia Vargas",
    "José Luna", "Silvia Morales", "Diana Acuña", "Tomás Delgado", "Camilo Ramírez",
    "Paula Torres", "Martín Flores", "Valentina Muñoz", "Renzo Salas", "Daniela Ruiz",
  ];
  const guestListLucia = [
    "María Castillo", "Roberto Ponce", "Lucero Peña", "Enrique Alva", "Cecilia Soto",
    "Nicolás Vera", "Patricia Núñez", "Ángel Chávez", "Lorena Silva", "Fabio Benites",
    "Tatiana Guzmán", "Sergio Arce", "Laura Campos", "Mateo Rojas", "Pamela Vidal",
    "Iván Flores", "Julia Cárdenas", "Marco Acosta", "Ariana Casas", "Hugo Pinto",
    "Elisa Durand", "Renzo Cabrera",
  ];
  const guestListValeria = ["Daniela Vega", "Camila Herrera", "Paola Pineda", "Romina Castro", "Andrea León", "Sofía Rojas", "María Torres", "Lucía Paredes"];
  const guestListJose = ["Ricardo Salazar", "Mario Cárdenas", "Jaime Benavides", "Fernando Peña", "Alfredo Soto", "Diego Paz"];
  const guestListMiguel = [
    "Paola Suárez", "Lorena Gutiérrez", "Marcos Valencia", "Giovanna García", "Fabián Mendoza",
    "Carlos Aranda", "Mónica Araujo", "Julio Calderón", "Ruth Delgado", "Camilo Pinto",
    "Diana Cabrera", "Rafael Torres", "Florencia Luna", "Pablo Vargas", "Valeria Nieto",
  ];

  const reservations = [
    {
      id: "TRL-2026-0718-0024",
      code: "TRL-2026-0718-0024",
      residentId: "resident-402",
      residentName: "Ana García",
      apartment: "402",
      areaId: "terrace",
      areaName: "Terraza",
      date: "2026-07-18",
      start: "17:00",
      end: "23:00",
      guestCount: 25,
      guestList: guestListAna,
      reason: "Celebración de cumpleaños",
      status: "pending_approval",
      paymentStatus: "verified",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-ana-420.jpg", type: "image/jpeg", size: 184320 },
      depositStatus: "held",
      amount: 420,
      reservationFee: 120,
      depositAmount: 300,
      approvalRequired: true,
      createdAt: "2026-07-12T08:52:00-05:00",
      paymentSubmittedAt: "2026-07-12T09:10:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Reglas aceptadas a las 08:55", "Comprobante Yape validado a las 09:12"],
    },
    {
      id: "EVR-2026-0712-0007",
      code: "EVR-2026-0712-0007",
      residentId: "resident-1203",
      residentName: "Miguel Castro",
      apartment: "1203",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-12",
      start: "18:00",
      end: "22:00",
      guestCount: 40,
      guestList: ["Lista registrada"],
      reason: "Reunión familiar",
      status: "completed",
      paymentStatus: "verified",
      paymentMethod: "Transferencia",
      paymentProof: { name: "transferencia-miguel.pdf", type: "application/pdf", size: 221184 },
      depositStatus: "retained",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-03T11:00:00-05:00",
      paymentSubmittedAt: "2026-07-03T13:00:00-05:00",
      approvedBy: "María Fernanda Rojas",
      approvedAt: "2026-07-03T16:20:00-05:00",
      securityResidentArrived: true,
      securityGuestsVerified: true,
      cleaningStatus: "completed",
      messages: ["Post evento con observación de silla dañada"],
    },
  ];

  const julyPlan = [
    { areaId: "terrace", count: 16, baseFee: 120, code: "TRL" },
    { areaId: "bbq", count: 22, baseFee: 60, code: "BBQ" },
    { areaId: "event-room", count: 7, baseFee: 200, code: "EVR" },
    { areaId: "coworking", count: 41, baseFee: 0, code: "COW" },
  ];

  let reservationCounter = 1;
  julyPlan.forEach((plan, areaIndex) => {
    for (let i = 0; i < plan.count; i += 1) {
      const code = `${plan.code}-2026-07-${String((i % 28) + 1).padStart(2, "0")}-${String(reservationCounter).padStart(4, "0")}`;
      if (code === "TRL-2026-07-18-0024") {
        reservationCounter += 1;
        continue;
      }
      const resident = residents[(areaIndex * 11 + i) % residents.length];
      const area = areas.find((item) => item.id === plan.areaId);
      const statuses = ["approved", "completed", "confirmed"];
      reservations.push({
        id: code,
        code,
        residentId: resident.id,
        residentName: resident.name,
        apartment: resident.apartment,
        areaId: area.id,
        areaName: area.name,
        date: `2026-07-${String((i % 28) + 1).padStart(2, "0")}`,
        start: area.id === "coworking" ? "09:00" : i % 2 === 0 ? "17:00" : "12:00",
        end: area.id === "coworking" ? "12:00" : i % 2 === 0 ? "21:00" : "16:00",
        guestCount: area.id === "coworking" ? 1 : Math.min(area.capacity - 2, 6 + (i % 14)),
        guestList: area.requiresGuestList ? ["Lista validada"] : [],
        reason: area.id === "coworking" ? "Bloque de trabajo" : "Reserva de uso común",
        status: statuses[i % statuses.length],
        paymentStatus: "verified",
        paymentMethod: i % 2 === 0 ? "Yape" : "Transferencia",
        paymentProof: null,
        depositStatus: area.deposit > 0 ? (i % 12 === 0 ? "retained" : i % 3 === 0 ? "released" : "held") : "released",
        amount: plan.baseFee + area.deposit,
        reservationFee: plan.baseFee,
        depositAmount: area.deposit,
        approvalRequired: area.requiresApproval,
        createdAt: `2026-07-${String((i % 28) + 1).padStart(2, "0")}T09:00:00-05:00`,
        paymentSubmittedAt: `2026-07-${String((i % 28) + 1).padStart(2, "0")}T10:00:00-05:00`,
        approvedBy: area.requiresApproval ? "María Fernanda Rojas" : null,
        approvedAt: area.requiresApproval ? `2026-07-${String((i % 28) + 1).padStart(2, "0")}T12:00:00-05:00` : null,
        securityResidentArrived: i % 5 !== 0,
        securityGuestsVerified: i % 6 !== 0,
        cleaningStatus: area.requiresCleaning ? (i % 4 === 0 ? "pending" : "completed") : "completed",
        messages: [],
      });
      reservationCounter += 1;
    }
  });

  reservations.push(
    {
      id: "TRL-2026-0716-0091",
      code: "TRL-2026-0716-0091",
      residentId: "resident-605",
      residentName: "José Torres",
      apartment: "605",
      areaId: "terrace",
      areaName: "Terraza",
      date: "2026-07-16",
      start: "18:00",
      end: "22:00",
      guestCount: 18,
      guestList: [],
      reason: "Cena de cumpleaños",
      status: "pending_approval",
      paymentStatus: "verified",
      paymentMethod: "Plin",
      paymentProof: null,
      depositStatus: "held",
      amount: 420,
      reservationFee: 120,
      depositAmount: 300,
      approvalRequired: true,
      createdAt: "2026-07-13T08:14:00-05:00",
      paymentSubmittedAt: "2026-07-13T08:40:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Solicita equipo de sonido apagado a las 10:00 PM"],
    },
    {
      id: "EVR-2026-0719-0094",
      code: "EVR-2026-0719-0094",
      residentId: "resident-808",
      residentName: "Valeria Mendoza",
      apartment: "808",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-19",
      start: "16:00",
      end: "21:00",
      guestCount: 32,
      guestList: ["Pendiente de carga"],
      reason: "Baby shower",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-valeria-700.jpg", type: "image/jpeg", size: 196608 },
      depositStatus: "held",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-14T14:20:00-05:00",
      paymentSubmittedAt: "2026-07-14T16:00:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Lista de invitados incompleta"],
    },
    {
      id: "EVR-2026-0720-0101",
      code: "EVR-2026-0720-0101",
      residentId: "resident-1507",
      residentName: "Lucía Fernández",
      apartment: "1507",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-20",
      start: "15:00",
      end: "21:00",
      guestCount: 22,
      guestList: guestListLucia,
      reason: "Aniversario familiar",
      status: "pending_approval",
      paymentStatus: "verified",
      paymentMethod: "Transferencia",
      paymentProof: { name: "transferencia-lucia-700.pdf", type: "application/pdf", size: 245760 },
      depositStatus: "held",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-15T09:20:00-05:00",
      paymentSubmittedAt: "2026-07-15T09:48:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Solicita confirmación temprana para coordinar decoración.", "Lista de invitados completa."],
    },
    {
      id: "EVR-2026-0724-0102",
      code: "EVR-2026-0724-0102",
      residentId: "resident-808",
      residentName: "Valeria Mendoza",
      apartment: "808",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-24",
      start: "17:00",
      end: "22:00",
      guestCount: 30,
      guestList: guestListValeria,
      reason: "Baby shower reprogramado",
      status: "pending_approval",
      paymentStatus: "rejected",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-valeria-borroso.jpg", type: "image/jpeg", size: 105472 },
      depositStatus: "held",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-16T10:30:00-05:00",
      paymentSubmittedAt: "2026-07-16T10:44:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Comprobante rechazado por imagen cortada.", "Lista parcial cargada; faltan 22 nombres."],
    },
    {
      id: "TRL-2026-0722-0103",
      code: "TRL-2026-0722-0103",
      residentId: "resident-605",
      residentName: "José Torres",
      apartment: "605",
      areaId: "terrace",
      areaName: "Terraza",
      date: "2026-07-22",
      start: "17:00",
      end: "21:00",
      guestCount: 14,
      guestList: guestListJose,
      reason: "Cena con amigos",
      status: "rejected",
      paymentStatus: "verified",
      paymentMethod: "Plin",
      paymentProof: { name: "plin-jose-420.jpg", type: "image/jpeg", size: 172032 },
      depositStatus: "held",
      amount: 420,
      reservationFee: 120,
      depositAmount: 300,
      approvalRequired: true,
      createdAt: "2026-07-15T12:15:00-05:00",
      paymentSubmittedAt: "2026-07-15T12:40:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      reasonNote: "Registro con observación de convivencia",
      messages: ["Reserva rechazada por antecedente de ruido en evento anterior."],
    },
    {
      id: "TRL-2026-0723-0104",
      code: "TRL-2026-0723-0104",
      residentId: "resident-1203",
      residentName: "Miguel Castro",
      apartment: "1203",
      areaId: "terrace",
      areaName: "Terraza",
      date: "2026-07-23",
      start: "12:00",
      end: "16:00",
      guestCount: 10,
      guestList: [],
      reason: "Almuerzo corporativo",
      status: "cancelled",
      paymentStatus: "verified",
      paymentMethod: "Transferencia",
      paymentProof: { name: "transferencia-miguel-420.pdf", type: "application/pdf", size: 215040 },
      depositStatus: "held",
      amount: 420,
      reservationFee: 120,
      depositAmount: 300,
      approvalRequired: true,
      createdAt: "2026-07-14T11:10:00-05:00",
      paymentSubmittedAt: "2026-07-14T11:35:00-05:00",
      approvedBy: "María Fernanda Rojas",
      approvedAt: "2026-07-14T13:00:00-05:00",
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      refundStatus: "pending",
      messages: ["Cancelada por viaje del residente. Reembolso aún no procesado."],
    },
    {
      id: "BBQ-2026-0725-0105",
      code: "BBQ-2026-0725-0105",
      residentId: "resident-402",
      residentName: "Ana García",
      apartment: "402",
      areaId: "bbq",
      areaName: "Zona BBQ",
      date: "2026-07-25",
      start: "12:00",
      end: "16:00",
      guestCount: 12,
      guestList: [],
      reason: "Parrilla dominical",
      status: "approved",
      paymentStatus: "verified",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-ana-bbq.jpg", type: "image/jpeg", size: 162816 },
      depositStatus: "held",
      amount: 210,
      reservationFee: 60,
      depositAmount: 150,
      approvalRequired: false,
      createdAt: "2026-07-18T09:00:00-05:00",
      paymentSubmittedAt: "2026-07-18T09:11:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: true,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Seguridad registró llegada; falta validación de invitados."],
    },
    {
      id: "TRL-2026-0710-0106",
      code: "TRL-2026-0710-0106",
      residentId: "resident-1507",
      residentName: "Lucía Fernández",
      apartment: "1507",
      areaId: "terrace",
      areaName: "Terraza",
      date: "2026-07-10",
      start: "17:00",
      end: "23:00",
      guestCount: 18,
      guestList: guestListLucia.slice(0, 18),
      reason: "Cena de despedida",
      status: "no_show",
      paymentStatus: "verified",
      paymentMethod: "Transferencia",
      paymentProof: { name: "transferencia-lucia-420.pdf", type: "application/pdf", size: 188416 },
      depositStatus: "held",
      amount: 420,
      reservationFee: 120,
      depositAmount: 300,
      approvalRequired: true,
      createdAt: "2026-07-05T14:10:00-05:00",
      paymentSubmittedAt: "2026-07-05T14:42:00-05:00",
      approvedBy: "María Fernanda Rojas",
      approvedAt: "2026-07-05T16:00:00-05:00",
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Seguridad esperó 30 minutos sin llegada del residente."],
    },
    {
      id: "EVR-2026-0711-0107",
      code: "EVR-2026-0711-0107",
      residentId: "resident-808",
      residentName: "Valeria Mendoza",
      apartment: "808",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-11",
      start: "16:00",
      end: "21:00",
      guestCount: 16,
      guestList: guestListValeria.concat(guestListMiguel.slice(0, 8)),
      reason: "Taller privado",
      status: "completed",
      paymentStatus: "verified",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-valeria-700-ok.jpg", type: "image/jpeg", size: 194560 },
      depositStatus: "released",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-04T10:10:00-05:00",
      paymentSubmittedAt: "2026-07-04T10:20:00-05:00",
      approvedBy: "María Fernanda Rojas",
      approvedAt: "2026-07-04T12:00:00-05:00",
      securityResidentArrived: true,
      securityGuestsVerified: true,
      cleaningStatus: "completed",
      messages: ["Evento cerrado sin observaciones relevantes."],
    },
    {
      id: "EVR-2026-0726-0108",
      code: "EVR-2026-0726-0108",
      residentId: "resident-1203",
      residentName: "Miguel Castro",
      apartment: "1203",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-26",
      start: "15:00",
      end: "20:00",
      guestCount: 15,
      guestList: guestListMiguel,
      reason: "Reunión de promoción",
      status: "confirmed",
      paymentStatus: "verified",
      paymentMethod: "Transferencia",
      paymentProof: { name: "transferencia-miguel-700.pdf", type: "application/pdf", size: 239616 },
      depositStatus: "held",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-18T13:15:00-05:00",
      paymentSubmittedAt: "2026-07-18T13:30:00-05:00",
      approvedBy: "María Fernanda Rojas",
      approvedAt: "2026-07-18T15:00:00-05:00",
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Reprogramada desde 2026-07-25 por cruce con proveedor externo."],
    },
    {
      id: "BBQ-2026-0727-0109",
      code: "BBQ-2026-0727-0109",
      residentId: "resident-402",
      residentName: "Ana García",
      apartment: "402",
      areaId: "bbq",
      areaName: "Zona BBQ",
      date: "2026-07-27",
      start: "08:00",
      end: "12:00",
      guestCount: 8,
      guestList: [],
      reason: "Desayuno del comité",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Plin",
      paymentProof: { name: "plin-ana-bbq.jpg", type: "image/jpeg", size: 118784 },
      depositStatus: "held",
      amount: 210,
      reservationFee: 60,
      depositAmount: 150,
      approvalRequired: false,
      createdAt: "2026-07-19T08:05:00-05:00",
      paymentSubmittedAt: "2026-07-19T08:18:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      messages: ["Comprobante recibido; pendiente validación administrativa."],
    },
    {
      id: "COW-2026-0728-0110",
      code: "COW-2026-0728-0110",
      residentId: "resident-605",
      residentName: "José Torres",
      apartment: "605",
      areaId: "coworking",
      areaName: "Coworking",
      date: "2026-07-28",
      start: "09:00",
      end: "12:00",
      guestCount: 1,
      guestList: [],
      reason: "Sesión de trabajo extendida",
      status: "confirmed",
      paymentStatus: "verified",
      paymentMethod: "Transferencia",
      paymentProof: null,
      depositStatus: "released",
      amount: 0,
      reservationFee: 0,
      depositAmount: 0,
      approvalRequired: false,
      createdAt: "2026-07-20T09:00:00-05:00",
      paymentSubmittedAt: "2026-07-20T09:00:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: true,
      securityGuestsVerified: true,
      cleaningStatus: "completed",
      messages: ["Uso gratuito regulado."],
    }
  );


  // Día operativo realista para dashboard: 120+ departamentos, 5 áreas comunes y alta carga de revisión.
  // Mantiene escenarios por área común en la fecha base de demo usada por el portal.
  const todayOperationalReservations = [
    {
      id: "TRL-2026-0712-0201",
      code: "TRL-2026-0712-0201",
      residentId: "resident-402",
      residentName: "Ana García",
      apartment: "402",
      areaId: "terrace",
      areaName: "Terraza",
      date: "2026-07-12",
      start: "09:00",
      end: "11:00",
      guestCount: 8,
      guestList: ["Mariela Costa", "Bruno Palacios", "Claudia Peña", "Raúl Benavides", "Sofía Rojas", "Mateo Casas", "Fiorella Durand", "Iván Ponce"],
      reason: "Desayuno familiar",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-terraza-ana-420.jpg", type: "image/jpeg", size: 148320 },
      depositStatus: "held",
      amount: 420,
      reservationFee: 120,
      depositAmount: 300,
      approvalRequired: true,
      createdAt: "2026-07-12T07:15:00-05:00",
      paymentSubmittedAt: "2026-07-12T07:26:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["pago_por_revisar", "aprobacion_del_mismo_dia"],
      messages: ["Reserva ingresada el mismo día; requiere aprobación rápida."],
    },
    {
      id: "TRL-2026-0712-0202",
      code: "TRL-2026-0712-0202",
      residentId: "resident-605",
      residentName: "José Torres",
      apartment: "605",
      areaId: "terrace",
      areaName: "Terraza",
      date: "2026-07-12",
      start: "12:00",
      end: "16:00",
      guestCount: 34,
      guestList: guestListJose.concat(["Mónica Vidal", "Renzo Prado", "Patricia Arce", "Gonzalo Vera", "Daniela Ponce", "Hugo Cárdenas", "Lucero Díaz", "Alonso Salas"]),
      reason: "Almuerzo con invitados",
      status: "pending_approval",
      paymentStatus: "verified",
      paymentMethod: "Plin",
      paymentProof: { name: "plin-jose-terraza-420.jpg", type: "image/jpeg", size: 166112 },
      depositStatus: "held",
      amount: 420,
      reservationFee: 120,
      depositAmount: 300,
      approvalRequired: true,
      createdAt: "2026-07-11T20:30:00-05:00",
      paymentSubmittedAt: "2026-07-11T20:45:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["alto_aforo", "antecedente_ruido"],
      messages: ["Aforo alto y antecedente operativo; requiere revisión manual."],
    },
    {
      id: "TRL-2026-0712-0203",
      code: "TRL-2026-0712-0203",
      residentId: "resident-808",
      residentName: "Valeria Mendoza",
      apartment: "808",
      areaId: "terrace",
      areaName: "Terraza",
      date: "2026-07-12",
      start: "17:00",
      end: "23:00",
      guestCount: 39,
      guestList: guestListValeria.concat(guestListMiguel).slice(0, 23),
      reason: "Cumpleaños adolescente",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Transferencia",
      paymentProof: { name: "transferencia-valeria-terraza.pdf", type: "application/pdf", size: 248576 },
      depositStatus: "held",
      amount: 420,
      reservationFee: 120,
      depositAmount: 300,
      approvalRequired: true,
      createdAt: "2026-07-12T08:05:00-05:00",
      paymentSubmittedAt: "2026-07-12T08:12:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["pago_por_revisar", "lista_invitados_incompleta", "cierre_tarde"],
      messages: ["Lista de invitados incompleta para el aforo declarado."],
    },
    {
      id: "BBQ-2026-0712-0204",
      code: "BBQ-2026-0712-0204",
      residentId: "resident-1203",
      residentName: "Miguel Castro",
      apartment: "1203",
      areaId: "bbq",
      areaName: "Zona BBQ",
      date: "2026-07-12",
      start: "08:00",
      end: "10:00",
      guestCount: 6,
      guestList: [],
      reason: "Desayuno en parrilla",
      status: "confirmed",
      paymentStatus: "verified",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-miguel-bbq-210.jpg", type: "image/jpeg", size: 132128 },
      depositStatus: "held",
      amount: 210,
      reservationFee: 60,
      depositAmount: 150,
      approvalRequired: false,
      createdAt: "2026-07-11T18:15:00-05:00",
      paymentSubmittedAt: "2026-07-11T18:18:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: true,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["limpieza_entre_turnos"],
      messages: ["Turno temprano requiere limpieza inmediata antes del siguiente bloque."],
    },
    {
      id: "BBQ-2026-0712-0205",
      code: "BBQ-2026-0712-0205",
      residentId: "resident-1507",
      residentName: "Lucía Fernández",
      apartment: "1507",
      areaId: "bbq",
      areaName: "Zona BBQ",
      date: "2026-07-12",
      start: "10:00",
      end: "14:00",
      guestCount: 18,
      guestList: [],
      reason: "Parrilla familiar",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Plin",
      paymentProof: { name: "plin-lucia-bbq-210.jpg", type: "image/jpeg", size: 119008 },
      depositStatus: "held",
      amount: 210,
      reservationFee: 60,
      depositAmount: 150,
      approvalRequired: false,
      createdAt: "2026-07-12T07:40:00-05:00",
      paymentSubmittedAt: "2026-07-12T07:44:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["pago_por_revisar", "casi_aforo_maximo"],
      messages: ["Pago enviado por Plin; pendiente verificación administrativa."],
    },
    {
      id: "BBQ-2026-0712-0206",
      code: "BBQ-2026-0712-0206",
      residentId: "resident-402",
      residentName: "Ana García",
      apartment: "402",
      areaId: "bbq",
      areaName: "Zona BBQ",
      date: "2026-07-12",
      start: "16:00",
      end: "20:00",
      guestCount: 21,
      guestList: [],
      reason: "Parrilla de cumpleaños",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-ana-bbq-aforo.jpg", type: "image/jpeg", size: 140224 },
      depositStatus: "held",
      amount: 210,
      reservationFee: 60,
      depositAmount: 150,
      approvalRequired: false,
      createdAt: "2026-07-12T08:20:00-05:00",
      paymentSubmittedAt: "2026-07-12T08:21:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["aforo_excedido", "pago_por_revisar"],
      messages: ["Aforo declarado supera capacidad de Zona BBQ."],
    },
    {
      id: "EVR-2026-0712-0207",
      code: "EVR-2026-0712-0207",
      residentId: "resident-605",
      residentName: "José Torres",
      apartment: "605",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-12",
      start: "08:00",
      end: "12:00",
      guestCount: 26,
      guestList: guestListJose.concat(guestListValeria, guestListMiguel).slice(0, 26),
      reason: "Reunión de promoción",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Transferencia",
      paymentProof: { name: "transferencia-jose-eventos-700.pdf", type: "application/pdf", size: 255120 },
      depositStatus: "held",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-11T21:15:00-05:00",
      paymentSubmittedAt: "2026-07-11T21:25:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["pago_por_revisar", "proveedor_externo"],
      messages: ["Solicita ingreso anticipado de decorador externo."],
    },
    {
      id: "EVR-2026-0712-0208",
      code: "EVR-2026-0712-0208",
      residentId: "resident-808",
      residentName: "Valeria Mendoza",
      apartment: "808",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-12",
      start: "12:30",
      end: "17:00",
      guestCount: 55,
      guestList: guestListLucia.concat(guestListMiguel, guestListAna).slice(0, 55),
      reason: "Baby shower",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-valeria-eventos-700.jpg", type: "image/jpeg", size: 178944 },
      depositStatus: "held",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-12T06:50:00-05:00",
      paymentSubmittedAt: "2026-07-12T06:59:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["pago_por_revisar", "alto_aforo", "lista_larga"],
      messages: ["Lista extensa; seguridad necesita búsqueda rápida por nombre."],
    },
    {
      id: "EVR-2026-0712-0209",
      code: "EVR-2026-0712-0209",
      residentId: "resident-1507",
      residentName: "Lucía Fernández",
      apartment: "1507",
      areaId: "event-room",
      areaName: "Salón de eventos",
      date: "2026-07-12",
      start: "22:00",
      end: "23:30",
      guestCount: 12,
      guestList: guestListLucia.slice(0, 12),
      reason: "After office tardío",
      status: "pending_approval",
      paymentStatus: "submitted",
      paymentMethod: "Yape",
      paymentProof: { name: "yape-lucia-eventos-tarde.jpg", type: "image/jpeg", size: 111616 },
      depositStatus: "held",
      amount: 700,
      reservationFee: 200,
      depositAmount: 500,
      approvalRequired: true,
      createdAt: "2026-07-12T08:45:00-05:00",
      paymentSubmittedAt: "2026-07-12T08:49:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "pending",
      riskFlags: ["fuera_de_horario", "pago_por_revisar"],
      messages: ["Solicitud fuera del horario permitido; debe bloquearse o pedir reprogramación."],
    },
    {
      id: "COW-2026-0712-0210",
      code: "COW-2026-0712-0210",
      residentId: "resident-402",
      residentName: "Ana García",
      apartment: "402",
      areaId: "coworking",
      areaName: "Coworking",
      date: "2026-07-12",
      start: "08:00",
      end: "10:00",
      guestCount: 1,
      guestList: [],
      reason: "Reunión virtual",
      status: "confirmed",
      paymentStatus: "verified",
      paymentMethod: "Sin pago",
      paymentProof: null,
      depositStatus: "released",
      amount: 0,
      reservationFee: 0,
      depositAmount: 0,
      approvalRequired: false,
      createdAt: "2026-07-11T22:10:00-05:00",
      paymentSubmittedAt: "2026-07-11T22:10:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: true,
      securityGuestsVerified: true,
      cleaningStatus: "completed",
      riskFlags: [],
      messages: ["Uso regular de coworking."],
    },
    {
      id: "COW-2026-0712-0211",
      code: "COW-2026-0712-0211",
      residentId: "resident-605",
      residentName: "José Torres",
      apartment: "605",
      areaId: "coworking",
      areaName: "Coworking",
      date: "2026-07-12",
      start: "10:00",
      end: "13:00",
      guestCount: 4,
      guestList: ["Cliente externo 1", "Cliente externo 2", "Cliente externo 3"],
      reason: "Reunión con clientes",
      status: "pending_approval",
      paymentStatus: "verified",
      paymentMethod: "Sin pago",
      paymentProof: null,
      depositStatus: "released",
      amount: 0,
      reservationFee: 0,
      depositAmount: 0,
      approvalRequired: false,
      createdAt: "2026-07-12T07:05:00-05:00",
      paymentSubmittedAt: "2026-07-12T07:05:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "completed",
      riskFlags: ["invitados_en_area_solo_residentes"],
      messages: ["Coworking marcado como solo residentes, pero se declararon invitados externos."],
    },
    {
      id: "COW-2026-0712-0212",
      code: "COW-2026-0712-0212",
      residentId: "resident-808",
      residentName: "Valeria Mendoza",
      apartment: "808",
      areaId: "coworking",
      areaName: "Coworking",
      date: "2026-07-12",
      start: "14:00",
      end: "18:00",
      guestCount: 1,
      guestList: [],
      reason: "Bloque de trabajo extendido",
      status: "confirmed",
      paymentStatus: "verified",
      paymentMethod: "Sin pago",
      paymentProof: null,
      depositStatus: "released",
      amount: 0,
      reservationFee: 0,
      depositAmount: 0,
      approvalRequired: false,
      createdAt: "2026-07-12T08:10:00-05:00",
      paymentSubmittedAt: "2026-07-12T08:10:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "completed",
      riskFlags: ["duracion_extendida_gratuita"],
      messages: ["Uso gratuito extendido; oportunidad para límite diario por departamento."],
    },
    {
      id: "GYM-2026-0712-0213",
      code: "GYM-2026-0712-0213",
      residentId: "resident-1203",
      residentName: "Miguel Castro",
      apartment: "1203",
      areaId: "gym",
      areaName: "Gimnasio",
      date: "2026-07-12",
      start: "06:00",
      end: "07:00",
      guestCount: 1,
      guestList: [],
      reason: "Turno de entrenamiento",
      status: "confirmed",
      paymentStatus: "verified",
      paymentMethod: "Sin pago",
      paymentProof: null,
      depositStatus: "released",
      amount: 0,
      reservationFee: 0,
      depositAmount: 0,
      approvalRequired: false,
      createdAt: "2026-07-11T20:00:00-05:00",
      paymentSubmittedAt: "2026-07-11T20:00:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: true,
      securityGuestsVerified: true,
      cleaningStatus: "completed",
      riskFlags: [],
      messages: ["Control de aforo simple para gimnasio."],
    },
    {
      id: "GYM-2026-0712-0214",
      code: "GYM-2026-0712-0214",
      residentId: "resident-1507",
      residentName: "Lucía Fernández",
      apartment: "1507",
      areaId: "gym",
      areaName: "Gimnasio",
      date: "2026-07-12",
      start: "07:00",
      end: "08:00",
      guestCount: 2,
      guestList: ["Entrenador externo"],
      reason: "Entrenamiento con coach",
      status: "pending_approval",
      paymentStatus: "verified",
      paymentMethod: "Sin pago",
      paymentProof: null,
      depositStatus: "released",
      amount: 0,
      reservationFee: 0,
      depositAmount: 0,
      approvalRequired: false,
      createdAt: "2026-07-12T06:10:00-05:00",
      paymentSubmittedAt: "2026-07-12T06:10:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "completed",
      riskFlags: ["tercero_en_area_no_reservable"],
      messages: ["Ingreso de entrenador externo requiere política clara."],
    },
    {
      id: "GYM-2026-0712-0215",
      code: "GYM-2026-0712-0215",
      residentId: "resident-605",
      residentName: "José Torres",
      apartment: "605",
      areaId: "gym",
      areaName: "Gimnasio",
      date: "2026-07-12",
      start: "18:00",
      end: "19:30",
      guestCount: 7,
      guestList: ["Vecino 1", "Vecino 2", "Vecino 3", "Vecino 4", "Vecino 5", "Vecino 6"],
      reason: "Entrenamiento grupal",
      status: "pending_approval",
      paymentStatus: "verified",
      paymentMethod: "Sin pago",
      paymentProof: null,
      depositStatus: "released",
      amount: 0,
      reservationFee: 0,
      depositAmount: 0,
      approvalRequired: false,
      createdAt: "2026-07-12T08:35:00-05:00",
      paymentSubmittedAt: "2026-07-12T08:35:00-05:00",
      approvedBy: null,
      approvedAt: null,
      securityResidentArrived: false,
      securityGuestsVerified: false,
      cleaningStatus: "completed",
      riskFlags: ["aforo_operativo_gimnasio", "uso_grupal"],
      messages: ["Gimnasio no es reservable, pero el edificio necesita visibilidad de aforo."],
    },
  ];
  reservations.push(...todayOperationalReservations);

  reservations.forEach((reservation) => {
    reservation.lifecycle = [
      { status: "created", label: "Reserva creada", createdAt: reservation.createdAt, actor: reservation.residentName },
      ...(reservation.status !== "pending_approval" ? [{ status: reservation.status, label: `Estado inicial: ${reservation.status}`, createdAt: reservation.approvedAt || reservation.createdAt, actor: reservation.approvedBy || "Sistema" }] : []),
    ];
    reservation.refundStatus = reservation.refundStatus || "not_applicable";
  });

  const lifecycleOverrides = {
    "TRL-2026-0722-0103": [
      { status: "created", label: "Reserva creada", createdAt: "2026-07-15T12:15:00-05:00", actor: "José Torres" },
      { status: "rejected", label: "Reserva rechazada", createdAt: "2026-07-15T18:30:00-05:00", actor: "María Fernanda Rojas", detail: "Antecedente operativo por ruido reiterado." },
    ],
    "TRL-2026-0723-0104": [
      { status: "created", label: "Reserva creada", createdAt: "2026-07-14T11:10:00-05:00", actor: "Miguel Castro" },
      { status: "approved", label: "Reserva aprobada", createdAt: "2026-07-14T13:00:00-05:00", actor: "María Fernanda Rojas" },
      { status: "cancelled", label: "Reserva cancelada", createdAt: "2026-07-16T09:00:00-05:00", actor: "Carlos Vega", detail: "Cambio de agenda del residente." },
    ],
    "TRL-2026-0710-0106": [
      { status: "created", label: "Reserva creada", createdAt: "2026-07-05T14:10:00-05:00", actor: "Lucía Fernández" },
      { status: "approved", label: "Reserva aprobada", createdAt: "2026-07-05T16:00:00-05:00", actor: "María Fernanda Rojas" },
      { status: "no_show", label: "Inasistencia registrada", createdAt: "2026-07-10T23:20:00-05:00", actor: "Puerta principal" },
    ],
    "EVR-2026-0724-0102": [
      { status: "created", label: "Reserva creada", createdAt: "2026-07-16T10:30:00-05:00", actor: "Valeria Mendoza" },
      { status: "payment_rejected", label: "Pago rechazado", createdAt: "2026-07-16T12:10:00-05:00", actor: "Carlos Vega", detail: "Imagen borrosa; no se distingue el número de operación." },
    ],
    "EVR-2026-0726-0108": [
      { status: "created", label: "Reserva creada", createdAt: "2026-07-18T13:15:00-05:00", actor: "Miguel Castro" },
      { status: "approved", label: "Reserva aprobada", createdAt: "2026-07-18T15:00:00-05:00", actor: "María Fernanda Rojas" },
      { status: "confirmed", label: "Reserva reprogramada", createdAt: "2026-07-19T10:00:00-05:00", actor: "Carlos Vega", detail: "Se movió desde el 25 al 26 por coordinación con proveedor." },
    ],
  };
  reservations.forEach((reservation) => {
    if (lifecycleOverrides[reservation.id]) reservation.lifecycle = lifecycleOverrides[reservation.id];
  });

  const paymentLedger = reservations
    .filter((reservation) => reservation.amount > 0)
    .map((reservation) => ({
      id: `payment-${reservation.id}-initial`,
      reservationId: reservation.id,
      reservationCode: reservation.code,
      type: reservation.paymentStatus === "verified" ? "payment_verified" : "payment_submitted",
      amount: reservation.amount,
      method: reservation.paymentMethod || "Transferencia",
      status: reservation.paymentStatus,
      createdAt: reservation.paymentSubmittedAt || reservation.createdAt,
      actor: reservation.paymentStatus === "verified" ? "Administración" : reservation.residentName,
    }));

  const depositLedger = reservations
    .filter((reservation) => reservation.depositAmount > 0)
    .map((reservation) => ({
      id: `deposit-${reservation.id}-initial`,
      reservationId: reservation.id,
      reservationCode: reservation.code,
      type: `deposit_${reservation.depositStatus}`,
      amount: reservation.depositAmount,
      status: reservation.depositStatus,
      createdAt: reservation.paymentSubmittedAt || reservation.createdAt,
      actor: "Administración",
      reason: reservation.depositStatus === "retained" ? "Retención histórica" : null,
    }));

  const maintenanceBlocks = [
    { id: "maintenance-bbq-0720", areaId: "bbq", areaName: "Zona BBQ", date: "2026-07-20", start: "08:00", end: "14:00", reason: "Mantenimiento preventivo de parrillas", status: "active", createdBy: "María Fernanda Rojas", createdAt: "2026-07-15T10:00:00-05:00" },
    { id: "maintenance-gym-0721", areaId: "gym", areaName: "Gimnasio", date: "2026-07-21", start: "07:00", end: "18:00", reason: "Revisión de equipos", status: "active", createdBy: "Carlos Vega", createdAt: "2026-07-16T11:30:00-05:00" },
  ];

  const areaClosures = [
    { id: "closure-terrace-0721", entityType: "area_closure", areaId: "terrace", areaName: "Terraza", date: "2026-07-21", start: "08:00", end: "12:00", reason: "Inspección municipal", status: "active", createdBy: "María Fernanda Rojas", createdAt: "2026-07-16T10:00:00-05:00" },
  ];

  const tasks = [
    {
      id: "task-prep-ana",
      type: "Preparación",
      reservationId: "TRL-2026-0718-0024",
      reservationCode: "TRL-2026-0718-0024",
      areaName: "Terraza",
      dueTime: "2026-07-18T15:00:00-05:00",
      assignedUser: "Equipo interno",
      status: "pending",
      notes: "Checklist previo antes de la reserva.",
      checklist: ["Mesas instaladas", "Sillas instaladas", "Contenedores listos", "Baño inspeccionado"],
      completedItems: [],
    },
    {
      id: "task-clean-ana",
      type: "Limpieza post evento",
      reservationId: "TRL-2026-0718-0024",
      reservationCode: "TRL-2026-0718-0024",
      areaName: "Terraza",
      dueTime: "2026-07-18T23:15:00-05:00",
      assignedUser: "Equipo interno",
      status: "pending",
      notes: "Cierre y limpieza posterior.",
      checklist: ["Basura retirada", "Mesas limpias", "Piso limpio", "Luces revisadas", "Área cerrada"],
      completedItems: [],
    },
    {
      id: "task-event-room-issue",
      type: "Inspección",
      reservationId: "EVR-2026-0712-0007",
      reservationCode: "EVR-2026-0712-0007",
      areaName: "Salón de eventos",
      dueTime: "2026-07-12T22:30:00-05:00",
      assignedUser: "Equipo interno",
      status: "completed",
      notes: "Se detectó silla rota.",
      checklist: ["Mobiliario revisado", "Fotos cargadas", "Incidente escalado"],
      completedItems: ["Mobiliario revisado", "Fotos cargadas", "Incidente escalado"],
    },
    {
      id: "task-prep-lucia",
      type: "Preparación",
      reservationId: "EVR-2026-0720-0101",
      reservationCode: "EVR-2026-0720-0101",
      areaName: "Salón de eventos",
      dueTime: "2026-07-20T13:00:00-05:00",
      assignedUser: "Equipo interno",
      status: "pending",
      notes: "Montaje previo con revisión de aforo y mobiliario.",
      checklist: ["Mesas desplegadas", "Sillas contadas", "Baños revisados", "Extintor verificado"],
      completedItems: [],
    },
    {
      id: "task-clean-lucia",
      type: "Limpieza post evento",
      reservationId: "EVR-2026-0720-0101",
      reservationCode: "EVR-2026-0720-0101",
      areaName: "Salón de eventos",
      dueTime: "2026-07-20T21:15:00-05:00",
      assignedUser: "Equipo interno",
      status: "pending",
      notes: "Requiere control de residuos por decoración externa.",
      checklist: ["Basura retirada", "Piso aspirado", "Vidrios limpios", "Área cerrada"],
      completedItems: [],
    },
    {
      id: "task-inspect-valeria",
      type: "Inspección",
      reservationId: "EVR-2026-0711-0107",
      reservationCode: "EVR-2026-0711-0107",
      areaName: "Salón de eventos",
      dueTime: "2026-07-11T21:20:00-05:00",
      assignedUser: "Equipo interno",
      status: "completed",
      notes: "Inspección final sin daños, pero con residuos fuera de horario.",
      checklist: ["Mobiliario revisado", "Fotos cargadas", "Depósito liberable"],
      completedItems: ["Mobiliario revisado", "Fotos cargadas", "Depósito liberable"],
    },
    {
      id: "task-clean-bbq-ana",
      type: "Limpieza post evento",
      reservationId: "BBQ-2026-0725-0105",
      reservationCode: "BBQ-2026-0725-0105",
      areaName: "Zona BBQ",
      dueTime: "2026-07-25T16:30:00-05:00",
      assignedUser: "Equipo interno",
      status: "pending",
      notes: "Se dejó utensilios por retirar.",
      checklist: ["Parrilla limpia", "Mesas limpias", "Bolsas retiradas", "Llaves entregadas"],
      completedItems: [],
    },
    {
      id: "task-prep-miguel",
      type: "Preparación",
      reservationId: "EVR-2026-0726-0108",
      reservationCode: "EVR-2026-0726-0108",
      areaName: "Salón de eventos",
      dueTime: "2026-07-26T13:30:00-05:00",
      assignedUser: "Equipo interno",
      status: "pending",
      notes: "Reserva reprogramada; validar layout actualizado.",
      checklist: ["Cronograma impreso", "Mesas numeradas", "Ingreso de proveedor confirmado"],
      completedItems: [],
    },
  ];

  const incidents = [
    {
      id: "incident-chair",
      type: "Silla dañada",
      reservationId: "EVR-2026-0712-0007",
      reservationCode: "EVR-2026-0712-0007",
      areaName: "Salón de eventos",
      apartment: "1203",
      residentName: "Miguel Castro",
      description: "Silla rota detectada durante la inspección posterior al evento.",
      evidence: ["Foto 1", "Foto 2"],
      createdBy: "Equipo interno",
      status: "pending_resolution",
      estimatedCost: 80,
      depositImpact: "Retener S/ 80",
      notes: ["Escalado a administración", "Pendiente validación de reposición"],
      createdAt: "2026-07-12T22:42:00-05:00",
    },
    {
      id: "incident-noise",
      type: "Ruido",
      reservationId: "TRL-2026-0716-0091",
      reservationCode: "TRL-2026-0716-0091",
      areaName: "Terraza",
      apartment: "605",
      residentName: "José Torres",
      description: "Queja por música alta después de la hora permitida.",
      evidence: ["Registro de seguridad"],
      createdBy: "Puerta principal",
      status: "open",
      estimatedCost: 0,
      depositImpact: "Sin impacto",
      notes: ["Advertencia enviada al residente"],
      createdAt: "2026-07-09T22:18:00-05:00",
    },
    {
      id: "incident-trash",
      type: "Limpieza incompleta",
      reservationId: "BBQ-2026-0725-0105",
      reservationCode: "BBQ-2026-0725-0105",
      areaName: "Zona BBQ",
      apartment: "402",
      residentName: "Ana García",
      description: "Se encontraron residuos y utensilios en la zona BBQ después del horario de cierre.",
      evidence: ["Checklist limpieza", "Foto residuos"],
      createdBy: "Equipo interno",
      status: "open",
      estimatedCost: 0,
      depositImpact: "Sin impacto",
      notes: ["Pendiente confirmar si procede advertencia escrita"],
      createdAt: "2026-07-25T16:45:00-05:00",
    },
    {
      id: "incident-guest-access",
      type: "Invitados no registrados",
      reservationId: "EVR-2026-0719-0094",
      reservationCode: "EVR-2026-0719-0094",
      areaName: "Salón de eventos",
      apartment: "808",
      residentName: "Valeria Mendoza",
      description: "La lista enviada no cubre el total declarado y seguridad reportó ingreso de visitantes sin validar.",
      evidence: ["Bitácora seguridad"],
      createdBy: "Puerta principal",
      status: "pending_resolution",
      estimatedCost: 0,
      depositImpact: "Sin impacto",
      notes: ["Pendiente respuesta del residente"],
      createdAt: "2026-07-19T16:30:00-05:00",
    },
    {
      id: "incident-glass",
      type: "Vidrio astillado",
      reservationId: "EVR-2026-0720-0101",
      reservationCode: "EVR-2026-0720-0101",
      areaName: "Salón de eventos",
      apartment: "1507",
      residentName: "Lucía Fernández",
      description: "Se detectó un vidrio lateral astillado durante la preparación del mobiliario.",
      evidence: ["Foto vidrio", "Checklist preparación"],
      createdBy: "Equipo interno",
      status: "resolved",
      estimatedCost: 120,
      depositImpact: "Retener S/ 120",
      notes: ["Repuesto solicitado", "Cierre administrativo levantado para esa fecha"],
      createdAt: "2026-07-20T13:10:00-05:00",
      resolution: "Se reemplazó el panel antes del evento con cargo parcial a garantía.",
      resolvedAt: "2026-07-21T10:00:00-05:00",
      resolvedBy: "María Fernanda Rojas",
    },
    {
      id: "incident-sound",
      type: "Uso no permitido de parlante",
      reservationId: "TRL-2026-0718-0024",
      reservationCode: "TRL-2026-0718-0024",
      areaName: "Terraza",
      apartment: "402",
      residentName: "Ana García",
      description: "Seguridad registró parlante externo pese a regla de convivencia para eventos nocturnos.",
      evidence: ["Foto seguridad", "Registro de ronda"],
      createdBy: "Puerta secundaria",
      status: "open",
      estimatedCost: 0,
      depositImpact: "Sin impacto",
      notes: ["Monitorear durante el evento"],
      createdAt: "2026-07-18T18:40:00-05:00",
    },
  ];

  const messages = [
    {
      id: "msg-ana",
      residentName: "Ana García",
      apartment: "402",
      relatedReservation: "TRL-2026-0718-0024",
      type: "Comprobante de pago",
      status: "verified",
      summary: "Yape recibido por S/ 420 y validado por administración.",
      time: "2026-07-12T09:12:00-05:00",
    },
    {
      id: "msg-valeria",
      residentName: "Valeria Mendoza",
      apartment: "808",
      relatedReservation: "EVR-2026-0719-0094",
      type: "Lista de invitados",
      status: "pending",
      summary: "Faltan nombres para completar el aforo declarado.",
      time: "2026-07-14T16:24:00-05:00",
    },
    {
      id: "msg-failed",
      residentName: "Sistema",
      apartment: "N/A",
      relatedReservation: "TRL-2026-0716-0091",
      type: "Plantilla fallida",
      status: "failed",
      summary: "Falló el envío de la plantilla de aprobación pendiente.",
      time: "2026-07-14T18:04:00-05:00",
    },
    {
      id: "msg-lucia-payment",
      residentName: "Lucía Fernández",
      apartment: "1507",
      relatedReservation: "EVR-2026-0720-0101",
      type: "Confirmación operativa",
      status: "pending",
      summary: "Solicita confirmación de montaje y acceso para proveedor de decoración.",
      time: "2026-07-15T10:12:00-05:00",
    },
    {
      id: "msg-valeria-rejected",
      residentName: "Valeria Mendoza",
      apartment: "808",
      relatedReservation: "EVR-2026-0724-0102",
      type: "Comprobante rechazado",
      status: "failed",
      summary: "Se notificó rechazo de pago, pero la plantilla no incluyó el motivo completo.",
      time: "2026-07-16T12:22:00-05:00",
    },
    {
      id: "msg-miguel-refund",
      residentName: "Miguel Castro",
      apartment: "1203",
      relatedReservation: "TRL-2026-0723-0104",
      type: "Reembolso",
      status: "pending",
      summary: "Residente consulta fecha estimada del reembolso por reserva cancelada.",
      time: "2026-07-16T09:40:00-05:00",
    },
    {
      id: "msg-jose-rejected",
      residentName: "José Torres",
      apartment: "605",
      relatedReservation: "TRL-2026-0722-0103",
      type: "Reserva rechazada",
      status: "verified",
      summary: "Se comunicó rechazo por antecedente operativo y política de convivencia.",
      time: "2026-07-15T18:35:00-05:00",
    },
    {
      id: "msg-bbq-submitted",
      residentName: "Ana García",
      apartment: "402",
      relatedReservation: "BBQ-2026-0727-0109",
      type: "Comprobante de pago",
      status: "pending",
      summary: "Plin recibido por S/ 210. Pendiente validar número de operación.",
      time: "2026-07-19T08:19:00-05:00",
    },
  ];


  tasks.push(
    { id: "task-clean-trl-0201", type: "Limpieza intermedia", reservationId: "TRL-2026-0712-0201", reservationCode: "TRL-2026-0712-0201", areaName: "Terraza", dueTime: "2026-07-12T11:15:00-05:00", assignedUser: "Equipo interno", status: "pending", notes: "Retirar residuos antes del siguiente bloque de terraza.", checklist: ["Mesas limpias", "Piso revisado", "Baño revisado"], completedItems: [] },
    { id: "task-prep-trl-0203", type: "Preparación", reservationId: "TRL-2026-0712-0203", reservationCode: "TRL-2026-0712-0203", areaName: "Terraza", dueTime: "2026-07-12T15:45:00-05:00", assignedUser: "Equipo interno", status: "pending", notes: "Aforo alto y evento nocturno; validar mobiliario y señalética.", checklist: ["Sillas contadas", "Luces revisadas", "Extintor visible", "Cartel de hora límite"], completedItems: [] },
    { id: "task-clean-bbq-0205", type: "Limpieza intermedia", reservationId: "BBQ-2026-0712-0205", reservationCode: "BBQ-2026-0712-0205", areaName: "Zona BBQ", dueTime: "2026-07-12T14:15:00-05:00", assignedUser: "Equipo interno", status: "pending", notes: "Alta rotación de parrilla durante el día.", checklist: ["Parrilla limpia", "Carbón retirado", "Basura retirada"], completedItems: [] },
    { id: "task-prep-evr-0208", type: "Preparación", reservationId: "EVR-2026-0712-0208", reservationCode: "EVR-2026-0712-0208", areaName: "Salón de eventos", dueTime: "2026-07-12T11:30:00-05:00", assignedUser: "Equipo interno", status: "pending", notes: "Lista larga y proveedor externo; validar acceso anticipado.", checklist: ["Mesas numeradas", "Lista impresa", "Ingreso proveedor coordinado"], completedItems: [] },
    { id: "task-clean-evr-0208", type: "Limpieza post evento", reservationId: "EVR-2026-0712-0208", reservationCode: "EVR-2026-0712-0208", areaName: "Salón de eventos", dueTime: "2026-07-12T17:15:00-05:00", assignedUser: "Equipo interno", status: "pending", notes: "Requiere cierre rápido antes del evento nocturno solicitado.", checklist: ["Basura retirada", "Piso limpio", "Baños revisados", "Fotos cargadas"], completedItems: [] }
  );

  incidents.push(
    { id: "incident-today-overcapacity-bbq", type: "Aforo excedido", reservationId: "BBQ-2026-0712-0206", reservationCode: "BBQ-2026-0712-0206", areaName: "Zona BBQ", apartment: "402", residentName: "Ana García", description: "El residente declaró 21 personas para un área con capacidad de 20.", evidence: ["Solicitud WhatsApp"], createdBy: "Sistema", status: "open", estimatedCost: 0, depositImpact: "Sin impacto", notes: ["Debe recomendar reducción de invitados o cambio de área"], createdAt: "2026-07-12T08:22:00-05:00" },
    { id: "incident-today-event-hours", type: "Horario fuera de política", reservationId: "EVR-2026-0712-0209", reservationCode: "EVR-2026-0712-0209", areaName: "Salón de eventos", apartment: "1507", residentName: "Lucía Fernández", description: "Solicitud termina 23:30 aunque la política cierra 22:00.", evidence: ["Solicitud WhatsApp"], createdBy: "Sistema", status: "open", estimatedCost: 0, depositImpact: "Sin impacto", notes: ["Debe bloquearse antes de llegar a aprobación"], createdAt: "2026-07-12T08:50:00-05:00" },
    { id: "incident-today-coworking-guests", type: "Uso externo en coworking", reservationId: "COW-2026-0712-0211", reservationCode: "COW-2026-0712-0211", areaName: "Coworking", apartment: "605", residentName: "José Torres", description: "Coworking es solo residentes, pero se registraron tres clientes externos.", evidence: ["Lista enviada"], createdBy: "Sistema", status: "pending_resolution", estimatedCost: 0, depositImpact: "Sin impacto", notes: ["Oportunidad para regla de invitados por área"], createdAt: "2026-07-12T07:08:00-05:00" },
    { id: "incident-today-gym-coach", type: "Tercero en gimnasio", reservationId: "GYM-2026-0712-0214", reservationCode: "GYM-2026-0712-0214", areaName: "Gimnasio", apartment: "1507", residentName: "Lucía Fernández", description: "Solicitud de ingreso para entrenador externo en área no reservable.", evidence: ["Mensaje residente"], createdBy: "Puerta principal", status: "open", estimatedCost: 0, depositImpact: "Sin impacto", notes: ["Definir si seguridad puede autorizar o escalar"], createdAt: "2026-07-12T06:20:00-05:00" }
  );

  messages.push(
    { id: "msg-today-payment-trl-0201", residentName: "Ana García", apartment: "402", relatedReservation: "TRL-2026-0712-0201", type: "Comprobante de pago", status: "pending", summary: "Yape por S/ 420 enviado a las 07:26; pendiente validación.", time: "2026-07-12T07:26:00-05:00" },
    { id: "msg-today-payment-trl-0203", residentName: "Valeria Mendoza", apartment: "808", relatedReservation: "TRL-2026-0712-0203", type: "Comprobante de pago", status: "pending", summary: "Transferencia por S/ 420; falta confirmar operación bancaria.", time: "2026-07-12T08:12:00-05:00" },
    { id: "msg-today-payment-bbq-0205", residentName: "Lucía Fernández", apartment: "1507", relatedReservation: "BBQ-2026-0712-0205", type: "Comprobante de pago", status: "pending", summary: "Plin por S/ 210 pendiente de revisión.", time: "2026-07-12T07:44:00-05:00" },
    { id: "msg-today-payment-bbq-0206", residentName: "Ana García", apartment: "402", relatedReservation: "BBQ-2026-0712-0206", type: "Comprobante de pago", status: "pending", summary: "Yape recibido, pero la reserva excede aforo.", time: "2026-07-12T08:21:00-05:00" },
    { id: "msg-today-payment-evr-0207", residentName: "José Torres", apartment: "605", relatedReservation: "EVR-2026-0712-0207", type: "Comprobante de pago", status: "pending", summary: "Transferencia por S/ 700 con proveedor externo pendiente.", time: "2026-07-11T21:25:00-05:00" },
    { id: "msg-today-payment-evr-0208", residentName: "Valeria Mendoza", apartment: "808", relatedReservation: "EVR-2026-0712-0208", type: "Comprobante de pago", status: "pending", summary: "Yape por S/ 700 para evento de 55 invitados.", time: "2026-07-12T06:59:00-05:00" },
    { id: "msg-today-payment-evr-0209", residentName: "Lucía Fernández", apartment: "1507", relatedReservation: "EVR-2026-0712-0209", type: "Comprobante de pago", status: "pending", summary: "Pago enviado para horario fuera de política.", time: "2026-07-12T08:49:00-05:00" }
  );

  maintenanceBlocks.push(
    { id: "maintenance-terrace-0712-lighting", areaId: "terrace", areaName: "Terraza", date: "2026-07-12", start: "11:00", end: "12:00", reason: "Revisión de luces antes de eventos de tarde", status: "active", createdBy: "Carlos Vega", createdAt: "2026-07-12T06:30:00-05:00" },
    { id: "maintenance-bbq-0712-gas", areaId: "bbq", areaName: "Zona BBQ", date: "2026-07-12", start: "14:00", end: "15:00", reason: "Cambio de balón y limpieza técnica", status: "active", createdBy: "Carlos Vega", createdAt: "2026-07-12T07:00:00-05:00" }
  );

  areaClosures.push(
    { id: "closure-gym-0712-cleaning", entityType: "area_closure", areaId: "gym", areaName: "Gimnasio", date: "2026-07-12", start: "12:00", end: "13:00", reason: "Limpieza profunda por alto uso", status: "active", createdBy: "María Fernanda Rojas", createdAt: "2026-07-12T07:30:00-05:00" }
  );

  const report = {
    month: "Julio 2026",
    reservationsByArea: [
      { area: "Terraza", total: 18 },
      { area: "Zona BBQ", total: 22 },
      { area: "Salón de eventos", total: 9 },
      { area: "Coworking", total: 41 },
    ],
    revenueByArea: [
      { area: "Terraza", total: 2160 },
      { area: "Zona BBQ", total: 1320 },
      { area: "Salón de eventos", total: 1800 },
    ],
    incidents: [
      { name: "Silla dañada", total: 1 },
      { name: "Queja por ruido", total: 2 },
      { name: "Limpieza tardía", total: 1 },
    ],
    topAreas: ["Coworking", "Zona BBQ", "Terraza"],
    satisfaction: 4.7,
  };

  const superAdmin = {
    buildings: [
      { id: "building-torres", name: "Edificio Torres del Parque", district: "Miraflores", plan: "Pilot 60 días", templates: "9/9 activas", status: "Activo", onboardingStep: 5, subscriptionStatus: "trial" },
      { id: "building-alameda", name: "Residencial Alameda 54", district: "San Borja", plan: "Onboarding", templates: "6/9 activas", status: "Configurando", onboardingStep: 3, subscriptionStatus: "pending" },
      { id: "building-central", name: "Condominio Central Park", district: "Surco", plan: "Prospecto", templates: "0/9 activas", status: "Pendiente", onboardingStep: 1, subscriptionStatus: "lead" },
    ],
    templates: [
      { id: "template-welcome", name: "Entrada principal", language: "es-PE", status: "Activa", body: "Hola {{nombre}}, bienvenida a Bricks Living." },
      { id: "template-approved", name: "Reserva aprobada", language: "es-PE", status: "Activa", body: "Tu reserva {{codigo}} fue aprobada." },
      { id: "template-payment", name: "Pago recibido", language: "es-PE", status: "Activa", body: "Recibimos el pago de {{monto}}." },
      { id: "template-rejected", name: "Comprobante rechazado", language: "es-PE", status: "Activa", body: "No pudimos validar el comprobante de {{codigo}}." },
    ],
    supportQueue: [
      { id: "support-template", building: "Torres del Parque", issue: "Revisar plantilla fallida", owner: "Operations", sla: "Hoy", status: "open" },
      { id: "support-import", building: "Residencial Alameda 54", issue: "Importación de residentes", owner: "Onboarding", sla: "24h", status: "in_progress" },
    ],
    subscriptions: [
      { id: "subscription-torres", buildingId: "building-torres", building: "Edificio Torres del Parque", plan: "Piloto", amount: 0, status: "trial", renewalDate: "2026-09-01" },
      { id: "subscription-alameda", buildingId: "building-alameda", building: "Residencial Alameda 54", plan: "Living Pro", amount: 690, status: "pending", renewalDate: "2026-08-01" },
    ],
  };

  return {
    building: {
      name: "Edificio Torres del Parque",
      district: "Miraflores, Lima",
      floors: 22,
      apartmentsCount: 168,
      basements: 3,
      administrator: "María Fernanda Rojas",
      assistant: "Carlos Vega",
      security: ["Puerta principal", "Puerta secundaria"],
      cleaning: "Equipo interno",
      language: "Español LATAM",
      currency: "PEN",
    },
    areas,
    residents,
    apartments,
    reservations,
    tasks,
    incidents,
    messages,
    paymentLedger,
    depositLedger,
    maintenanceBlocks,
    areaClosures,
    report,
    superAdmin,
    auditLog: [],
  };
};
